# Title of your site
title = "XoYo24"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"
theme = "keep_it"
paginate = 5
enableEmoji = true
enableRobotsTXT = true

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = ""

# Enable comments by entering your Disqus shortname
# disqusShortname = ""

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

############################
## Advanced options below ##
############################
# Get last modified date for content from Git?
enableGitInfo = false
# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
footnotereturnlinkcontents = "↩"

[author]
  name = "xoyo24"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[permalinks]
    post = "/:year/:month/:slug"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
