# see https://gohugo.io/getting-started/configuration/ .
title = "XoYo24"
baseurl = "https://zen-yonath-d0cf2b.netlify.com/"
theme = "jane"
enableEmoji = true
enableRobotsTXT = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓
# Used only for Seo schema 
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
disqusShortname = "xoyo24"      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
enableGitInfo = true      # Get last modified date for content from Git?
# uglyURLs = true           # more info: https://gohugo.io/content-management/urls/#ugly-urls

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"    # en / ja/ zh-cn / ..

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[author]
  name = "XIAO Yang"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[permalinks]
    post = "/:year/:month/:day/:slug"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
