# Title of your site
title = "XoYo24"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://xoyo24.fun/"
theme = "hermit"
paginate = 15
enableEmoji = true
enableRobotsTXT = true
comment = true            # 是否开启评论
toc = true                # 是否开启目录
autoCollapseToc = true   # Auto expand and collapse toc
rssLimit = 100

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = ""
# disqusShortname = ""

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

############################
## Advanced options below ##
############################
# Get last modified date for content from Git?
enableGitInfo = false
# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"    # en / ja/ zh-cn / ..
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
footnotereturnlinkcontents = "↩"


# pygmentsCodeFencesGuessSyntax = true
# pygmentsStyle = "native"
pygmentsUseClasses = true
pygmentsCodeFences = true

[author]
  name = "XIAO Yang"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[taxonomies]
  tag = "tags"
  # category = "categories"
  # author = "authors"

[permalinks]
    post = "/:year/:month/:day/:slug"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
