[en]
  languageName = "English"
  contentDir = "content/en"

[zh-cn]
  languageName = "中文"
  contentDir = "content/zh"
  languageCode = "zh-Hans"
  # title = "Chinese website title..."

# [ja]
#   languageCode = "ja"
#   languageName = "🇯🇵"
#   contentDir = "content/ja"
#   title = "Japanese website title..."
