[en]
  languageName = "English"
  contentDir = "content/en"

[zh]
  languageName = "中文"
  contentDir = "content/zh"
  defaultContentLanguage = "zh-cn"    # en / ja/ zh-cn / ..
  # title = "Chinese website title..."

# [ja]
#   languageCode = "ja"
#   languageName = "🇯🇵"
#   contentDir = "content/ja"
#   title = "Japanese website title..."
