[en]
  languageCode = "en-us"
  contentDir = "content/en"

[ja]
  languageCode = "ja"
  contentDir = "content/ja"
  # title = "Japanese website title..."

[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  # title = "Chinese website title..."
