# Theme config
since = 2016
author = "xoyo24"               # Author's name
subtitle = "A Hugo theme"       # Subtitle
# cdn_url = ""           # Base CDN URL
# home_mode = "post"

# site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
keywords = ["Hugo", "theme","even"]
description = "Hugo theme even example site."

# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
dateFormatToUse = "2006-01-02"

google_verification = ""
bing_verification = ""
yandex_verification = ""
pinterest_verification = ""
baidu_verification = ""

avatar = "/images/me/avatar.png" #comment it to use gravatar
socialShare = true

license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[gravatar]
  #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar

[social]
  GitHub = "xoyo24"
  Linkedin = "xoyo24"
  Twitter = "xoyo24"
  #Instagram = "xxxx"
  #Email   = "xxxx"
  Facebook = "xoyo24"
  #Telegram = "xxxx"
  #Medium = "xxxx"
  #Gitlab = "xxxx"
  #Youtubelegacy = "xxxx"
  #Youtubecustom = "xxxx"
  #Youtubechannel = "xxxx"
  #Tumblr ="xxxx"
  #Quora = "xxxx"
  #Keybase = "xxxx"
  #Pinterest = "xxxx"
  #Reddit = "xxxx"
  #Codepen = "xxxx"
  #Bitbucket = "xxxx"
  #Stackoverflow = "xxxxx"
  #Weibo = "xxxx"
  #Odnoklassniki = "xxxx"
  #VKontakte = "xxxx"
  #Flickr = "xxxx"
  #Xing = "xxxx"
  #Snapchat = "xxxx"
  #Soundcloud = "xxxx"
  #Spotify = "xxxx"
  #Bandcamp = "xxxx"
  #Paypal = "xxxx"
  #Fivehundredpx = "xxxx"
  #Mix = "xxxx"
  #Goodreads = "xxxx"
  #Lastfm = "xxxx"
  #Foursquare = "xxxx"
  #Hackernews = "xxxx"
  #Kickstarter = "xxxx"
  #Patreon = "xxxx"
  #Steam = "xxxx"
  #Twitch = "xxxx"
  #Strava = "xxxx"
  #Skype = "xxxx"
  #Whatsapp = "xxxx"
  #Zhihu = "xxxx"
  #Douban = "xxxx"
  #Angellist = "xxxx"
  #Slidershare = "xxxx"
  #Jsfiddle = "xxxx"
  #Deviantart = "xxxx"
  #Behance = "xxxx"
  #Dribble = "xxxx"
  #Wordpress = "xxxx"
  #Vine = "xxxx"
  #Googlescholar = "xxxx"
  #Researchgate = "xxxx"
  #Mastodon = "xxxx"
  #Thingiverse = "xxxx"

[share]
  Twitter = true
  Facebook = true
  #Reddit = true
  Linkedin = true
  #Pinterest = true
  #HackerNews = true
  #Mix = true
  #Tumblr = true
  #VKontakte = true
  #Douban = true
  #Weibo = true

[gitalk]
  owner = ""
  repo = ""
  clientId = ""
  clientSecret = ""