# Theme config
since = 2020
homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
rssFullContent = true     # if false, Rss feed instead of the summary
mainSections = ["post"]

# site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
keywords = ["Blog", "xoyo24", "scala", "akka", "play framework", "git", "programming", "software", "engineering", "Development", "Scala", "Akka", "Actor Modle", "Elixir", "Microservices", "Docker", "Kubernetes"]
description = "Personnal blog for xoyo24. Software Development Engineer base in Japan. Mainly foucus Functinal Programming/Distributed System/Software Architecture"

archive-paginate = 30

# The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
dateFormatToUse = "2006-01-02"

# show word count and read time ?                       # 是否显示字数统计与阅读时间
moreMeta = true

# show language chooser in menu
showMenuLanguageChooser = true

# showAuthorInfo = true # show author info below the article

# 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
# Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
toc = true                                                                            # 是否开启目录
photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
katex = false             # see https://github.com/KaTeX/KaTeX
contentCopyright = 'Released under <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>.' 

[utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "xoyo24/blog"    # The repo to store comments
    issueTerm = "pathname"

[gitInfo]
    gitRepo = "https://github.com/xoyo24/blog"
    showCommitMessage = false

[social]
  c-twitter = "https://twitter.com/xoyo24"
  g-github = "https://github.com/xoyo24"
  # b-stack-overflow = "http://localhost:1313"
  # e-linkedin = "http://localhost:1313"
  # s-mastodon = "http://localhost:1313"
